### ISSUE TITLE
Is this the same netaddr as http://rubygems.org/gems/netaddr?

### ISSUE THREAD

**Issue by aramprice** [bensie/netaddr#1]
We recently ran into a problem with this gem where rails would not auto-load it because the namespace and filenames do not follow conventions. Ex (`NetAddr` => `net_addr.rb` or `netaddr.rb` => `Netaddr`.

If you are currently maintaining the gem, would you be open to a PR to add a shim that adds support for the naming convention? Ex:

in `netaddr.rb`

``` ruby
# ...

Netaddr = NetAddr
```

A more radical approach would be to rename the gem to `net_addr`.

thanks,

aram

**Comment by bensie** [comment]
No, this is just a fork -- the code wasn't on GitHub and we needed to make some modifications as well :)

**Comment by bensie** [comment]
I think it's pretty much unmaintained, so if you want to PR against my fork, good with me....maybe we can get a hold of the original maintainer eventually.

**Comment by aramprice** [comment]
@bensie,

Thanks for the response!

We ended up working around the (minor) annoyance this was causing.

Its probably not worth it (for me/us) at this point to take up maintenance patches on the project if no one is actively working on it. I might pitch in though if someone ever gets the ball rolling.

thanks,

aram
