### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [bensie/netaddr#3]
Under which license is this code?

**Comment by cghsystems** [comment]
I would like to bump this issue.

**Comment by bensie** [comment]
From the Rubyforge page: http://netaddr.rubyforge.org/classes/NetAddr.html

```
Copyleft (c) 2006 Dustin Spinhirne

Licensed under the same terms as Ruby, No Warranty is provided.
```

**Comment by reiz** [comment]
@bensie Why not adding the license to the gemspec? That way it would show up in RubyGems and the people don't have to start a manual research project to find the license ;-)

**Comment by bensie** [comment]
@reiz I don't own the gem. This repo is just a fork of the code for reference. Back when I put this on GitHub, he was unreachable.

**Comment by reiz** [comment]
Hm. Ok. That one of that kind of projects :-/
